baseURL: "https://thenoesis12.netlify.app"
languageCode: "en-us"
title: "The Noesis"
pygmentsstyle: 'monokai'
enableEmoji: true
paginate: 10
social:
  twitter: "https://twitter.com/thenoesiske"
  github: ""
  instagram: "https://instagram.com/thenoesiske"
  linkedin: ""
  dribbble: ""
  youtube: ""
params:
  description: "A Tech and Science Oasis"
  images: "images/about.png"
  hero: "images/about.png"
taxonomies:
  author: authors
  tag: tags
  category: categories
markup:
  goldmark:
    renderer:
      unsafe: true
related:
  threshold: 0
  includeNewer: true
  toLower: false
  indices:
  - name: categories
    weight: 500
  - name: tags
    weight: 200
  - name: keywords
    weight: 300
  - name: date
    weight: 10
    
