baseURL: "https://thenoesiske.netlify.app"
languageCode: "en-us"
title: "The Noesis"
pygmentsstyle: 'monokai'
enableEmoji: true
paginate: 20

social:
  twitter: "https://twitter.com/thenoesiske"
  github: ""
  instagram: "https://instagram.com/thenoesiske"
  linkedin: ""
  dribbble: ""
  youtube: ""
  
params:
  description: "A Tech and Science Oasis"
  images: "images/about.png"
  hero: "images/about.png"
  GithubEdit: "https://github.com/owlsecco/thenoesis12/edit/master/content/"
  
taxonomies:
  author: authors
  tag: tags
  category: categories
  
markup:
  goldmark:
    renderer:
      unsafe: true
      
related:
  threshold: 0
  includeNewer: true
  toLower: false
  indices:
  - name: categories
    weight: 500
  - name: tags
    weight: 200
  - name: keywords
    weight: 300
  - name: date
    weight: 10
    
outputFormats:
  SearchIndex:
    baseName: search
    mediaType: application/json

outputs:
  home:
    - HTML
    - RSS
    - SearchIndex
    
